name: CI/CD - Backend Ventas

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Build, Push y Deploy - Ventas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen ms-ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ev2-kcd-ms-ventas:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ev2-kcd-ms-ventas:latest
            docker stop ms-ventas || true
            docker rm ms-ventas || true
            docker network create backend-net || true
            docker run -d \
              --name ms-ventas \
              --network backend-net \
              --restart unless-stopped \
              -p 8082:8082 \
              -e DB_ENDPOINT=mysqldb \
              -e DB_PORT=3306 \
              -e DB_NAME=ventas_db \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/ev2-kcd-ms-ventas:latest
