name: CI/CD Deploy - EJKEVIN

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ejkevin-frontend:latest
          build-args: |
            VITE_API_DESPACHO=${{ secrets.VITE_API_DESPACHO }}
            VITE_API_VENTAS=${{ secrets.VITE_API_VENTAS }}

      - name: Build y Push imagen ms-despacho
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ejkevin-ms-despacho:latest

      - name: Build y Push imagen ms-ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ejkevin-ms-ventas:latest

      - name: Deploy en EC2 Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/EJKEVIN
            git pull origin deploy
            cat > .env <<EOF
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            DB_USERNAME=root
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            VITE_API_DESPACHO=${{ secrets.VITE_API_DESPACHO }}
            VITE_API_VENTAS=${{ secrets.VITE_API_VENTAS }}
            EOF
            docker compose pull ms-despacho ms-ventas mysql
            docker compose up -d mysql ms-despacho ms-ventas

      - name: Deploy en EC2 Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/EJKEVIN
            git pull origin deploy
            cat > .env <<EOF
            VITE_API_DESPACHO=${{ secrets.VITE_API_DESPACHO }}
            VITE_API_VENTAS=${{ secrets.VITE_API_VENTAS }}
            EOF
            docker compose pull frontend
            docker compose up -d frontend
